### ISSUE TITLE
Programm compilation error

### ISSUE THREAD

**Issue by TurtleForGaming** [compujuckel/nspire-io#5]
I'm wrote this .cpp program:

```
#include <os.h>
#include <nspireio/nspireio.h>
int main(void)
{
        uart_puts("Nspire I/O testing tool\n");
        uart_printf("Compiled %s %s\n",__DATE__,__TIME__);
        wait_key_pressed();
        return 0;
}
```
And when I compile it give me this error:
```
mkdir -p .
nspire-ld hello.o -o ./helloworld-cpp.elf -Wl,-lnspireio
hello.o: In function `main':
hello.cpp:(.text.startup+0x8): undefined reference to `uart_puts(char const*)'
hello.cpp:(.text.startup+0x18): undefined reference to `uart_printf(char*, ...)'
collect2: error: ld a retourné le statut de sortie 1
Makefile:39 : la recette pour la cible « helloworld-cpp.elf » a échouée
make: *** [helloworld-cpp.elf] Erreur 1

```
What I'm doing wrong ?

**Comment by compujuckel** [comment]
If you are using the Nspire I/O version that is shipped with the Ndless SDK, it is actually using Vogtinators fork: https://github.com/Vogtinator/nspire-io/

I am not sure if the uart_* functions are still supported in his fork, but those are probably not what you are looking for.
The UART functions are not printing to the screen but rather to the serial port which would require soldering to actually see it write something on real hardware or use an emulator.

Use the functions starting with nio_* to print something to the screen.

I don't have an Ndless development environment set up at the moment, so I won't really be able to help much further. Maybe @Vogtinator could give some hints.

**Comment by Vogtinator** [comment]
> hello.cpp:(.text.startup+0x8): undefined reference to `uart_puts(char const*)'

Looks like a missing ```extern "C"``` somewhere, arch-nspire.o includes those symbols:
```
> nm arch-nspire/nspire-uart.o 
         U hwtype
         U idle
         U memset
0000004c T uart_getchar
0000034c T uart_gets
00000120 T uart_getsn
00000690 T uart_printf
0000055c T uart_putchar
000005e0 T uart_puts
00000000 T uart_ready
         U vsprintf
```

**Comment by TurtleForGaming** [comment]
Sorry It was my fault I wasn't correctly defining the lib
