### ISSUE TITLE
uart reading is not blocking in test.c

### ISSUE THREAD

**Issue by nbenm** [compujuckel/nspire-io#8]
I have tried an extract from test.c. This one:
```
	uart_puts("Enter text: ");
	uart_getsn(input,100);
	uart_printf("Your text was: %s\n",input);
```
The problem is that uart_getsn that uses uart_getchar is not blocking as expected. The uart_printf is executed, and the program exits.
What am I doing wrong ?
I'm using a TI-Nspire CX CAS

**Comment by nbenm** [comment]
After reading [This issue](https://github.com/compujuckel/nspire-io/issues/6)
I have changed line 34.
It works fine now.
@Vogtinator I'm using now your branch. It would be nice if you could change this.

**Comment by Vogtinator** [comment]
@nbenm Feel free to open a pull request.
