### ISSUE TITLE
How to clean uart buffer

### ISSUE THREAD

**Issue by nbenm** [compujuckel/nspire-io#9]
I'm trying to communicate with an esp8266.
Responses ends with "OK\r\n".
But it looks like the buffer is still containing garbage.
Is there a way to flush remaining data (ie ignore it)?

I don't know if this is good, I've written a uart_getsn clone but which waits for "\r\n"
If response is OK\r\n then I can send a new command to the esp8266. But the esp8266 says its busy.
I think this is because the buffer is not empty (I've seen this with a logic analyzer).

Maybe I'm wrong with this.

Thanks for any help

**Comment by TurtleForGaming** [comment]
For my use (Sending sms with the calc) I rewrote the uart_get_sn to wait until a termination char in this cas "\n"
```
char* uart_getsn_mdf(char* str, int num) {
        int i = 0;
        int max = num-1;
        while(1) {
                while(uart_ready()) {
                        if(i == max) {
                                str[i] = 0;
                                return str;
                        }
                        char c = uart_getchar();
                        str[i] = c;
                        if(c == '\b'){  i -= 2; }
                        else if(c == '\r')      { str[i] =0; return str; }
                        i++;
                }
        }
}
```
Be aware that to use `uart_ready()` you need a modified verison of nspire-io, I don't know if it has been fixed but for me it was always returning that there was data ready

**Comment by compujuckel** [comment]
uart_ready bug fixed in c74b476, PR for Vogtinators fork created: https://github.com/Vogtinator/nspire-io/pull/4
Let me know if that fixes your issue, otherwise please tell in more detail what you are trying to do, how the esp8266 "says" it's busy, etc.

Also keep in mind that the UART code hasn't been tested (at least not by me) on real CX hardware.

**Comment by TurtleForGaming** [comment]
It has been tested by me (More infos here https://codewalr.us/index.php?topic=2299.0 )

**Comment by nbenm** [comment]
First of all forget all I said before.
I'm aleady using the good uart_ready.
Here's what I'm trying (small test)
1 - send to the esp8266 the string "AT+GMR\r\n" (which means give me your version #)
2 - receive from the esp8266 the answer "AT+GMR\r\r\n00200.9.4\r\n\r\nOK\r\n" (ver # is 00200.9.4)

note that:
1 - AT command sent ends with "\r\n"
2 - answer from the esp begins with "AT+GMR\r\r\n" this is because of the echo ON.  
    note also an extra "\r". This always happen, even if I communicate via a serial console.
3 - the real end of message is "OK\r\n" (or ERROR...)

When using the current uart_getsn, response is sliced on "\r". So next part received begins with "\n".
So I have changed uart_getsn, and wrote uart_gets_crlf

```
char* uart_getscrlf(char* str, int num)
{
        int i;
        bool last_was_cr = FALSE;
        for(i = 0; i < num-1; i++)
        {
                char c = uart_getchar();
                str[i] = c;
                if(c == '\b')
                {
                        uart_puts(" \b");
                        i -= 2;
                }
                else if(c == '\r')
                {
                        last_was_cr = TRUE;
                }
                else if(c == '\n')
                {
                        if (last_was_cr) {
                                str[i-1] = 0;
                                uart_putchar('\n');
                                return str;
                        }
                        last_was_cr = FALSE;
                }
        }
        str[num] = 0;
        return str;
}
```
Each part ends now with "\r\n"
Here's the code I use for testing (I've tried many others)
```
#include <nspireio/nspireio.h>  
  
#include "test-esp8266.h"  
  
int main()  
{  
  char input[100] = {0};  
  bool is_ok;  
  is_ok = false;
  rst=0;
  nio_printf("Sending AT+GMR command...\n");
  uart_puts("AT+GMR\r\n");
  while (!is_ok) {
    uart_getscrlf(input,1000);
    nio_printf("Response from esp8266 is : %s\n",input);
    if (strcmp(input,"OK") == 0) is_ok=true;
  }

  puts("Bye!");
  wait_key_pressed();
  return 0;
}

```

But when I execute it using a logic analyzer, I have the result in csv file uploaded [here](https://filebin.net/61hfw66qg1x2lrb4/test.csv?t=pm711cr7)
First column is what I send to the esp, the second is what I receive from it.
As you can see:
1 - sent and received data are intermingled
2 - once all is finished, the AT command seems to be sent again. The esp first replies he is busy, and then the good response, and then sends what I'm calling garbage.

If I stop the processing after this first command, it works fine. I ignore the garbage.
But if I send a new AT command, let's say "AT\r\n", I'm waiting for "OK\r\n".
But I have:

1 - good response to AT+GMR
2 - garbage
3 - AT command sent
4 - good response to AT command
5 - garbage

I would like to stop after the first good results.

Can this be done by reading all the buffer for each command, using the necessary part, and then flushing the rest ?
If so how can this be done ?
Is there an other way to achieve this ?

**Comment by nbenm** [comment]
Ok. That's good now.
It didn't work after removing the line. But I saw in the logic analyser a "\n" beeing sent.
Based on what you said, I searched. It was this one https://github.com/compujuckel/nspire-io/blob/master/arch-nspire/nspire-uart.c#L62. After removing it, all works fine.
I understand now why:
- commands seemed to be sent twice
- when using the code with a serial console, all went fine.
Thanks for your help.
One question remains, do uart_getchar and uart_getsn need to be modified or not in the repo ?
Maybe an option. the esp does it by default, but "ATE0" is echo OFF, and "ATE1" is echo ON.

**Comment by compujuckel** [comment]
Glad it's working now!
Yes, an option to disable echo would be a good idea (preferably without changing the existing function signatures). I don't have the Ndless SDK set up, but I'll gladly accept a pull request if you want to work on this.
